# Source of truth for the site content. Transcribed from the Google Doc
# "October 2026 General Conference — Study Guide" (Saturday sessions, from recaps).
# Personal application sections and private notes are intentionally EXCLUDED.
# Quotes are copied verbatim from the doc (as reported in recaps). Do not add quotes
# that are not in the doc. Replace with official text once posted.
import json, pathlib

SAT_AM = "https://www.churchofjesuschrist.org/study/general-conference/2026/10/saturday-morning-session?lang=eng"
SAT_PM = "https://www.churchofjesuschrist.org/study/general-conference/2026/10/saturday-afternoon-session?lang=eng"
SUN_AM = "https://www.churchofjesuschrist.org/study/general-conference/2026/10/sunday-morning-session?lang=eng"
SUN_PM = "https://www.churchofjesuschrist.org/study/general-conference/2026/10/sunday-afternoon-session?lang=eng"
CN = "https://www.thechurchnews.com/general-conference/2026/10/03/"

sessions = [
  {"id": "sat-am", "color": "dawn", "name": "Saturday Morning Session", "when": "Sat, Oct 3 · 10:00am–noon MDT", "url": SAT_AM, "status": "complete",
   "note": "Conducted by President Henry B. Eyring. Music by The Tabernacle Choir at Temple Square."},
  {"id": "sat-pm", "color": "amber", "name": "Saturday Afternoon Session", "when": "Sat, Oct 3 · 2:00–4:00pm MDT", "url": SAT_PM, "status": "complete",
   "note": "Conducted by Elder Neil L. Andersen. Music by a choir from Northern Utah."},
  {"id": "sun-am", "color": "sky", "name": "Sunday Morning Session", "when": "Sun, Oct 4 · 10:00am–noon MDT", "url": SUN_AM, "status": "complete",
   "note": "Conducted by President D. Todd Christofferson. Music by The Tabernacle Choir at Temple Square (opening hymn: How Firm a Foundation; includes Music & the Spoken Word). Closed by President Dallin H. Oaks."},
  {"id": "sun-pm", "color": "violet", "name": "Sunday Afternoon Session", "when": "Sun, Oct 4 · 2:00–4:00pm MDT", "url": SUN_PM, "status": "pending",
   "note": "In progress. Conducted by Elder Gérald Caussé. Music by The Tabernacle Choir at Temple Square (opening hymn: Let Zion in Her Beauty Rise; choir: Love Will Bless Our Home). Talks added from Church News recaps as they post."},
]

def t(id, session, order, speaker, calling, title, recap, summary, scriptures, quotes, invitation, ponder, official_url=None):
    recap_url = recap if recap.startswith("http") else CN + recap
    return dict(id=id, session=session, order=order, speaker=speaker, calling=calling, title=title,
                recap_url=recap_url, official_url=official_url, summary=summary, scriptures=scriptures,
                quotes=quotes, invitation=invitation, ponder=ponder)

talks = [
 t("sat-am-1-gong", "sat-am", 1, "Elder Gerrit W. Gong", "Quorum of the Twelve Apostles", "Come to the Lord in His Holy House",
   "elder-gerrit-w-gong-october-2026-general-conference-come-to-the-lord-holy-house-temple/",
   "In a world of commotion and contention, the Lord invites us to a place of spiritual safety, harmony and holiness — His holy house. Agency, faith, repentance and Christ's Atonement make change and forgiveness possible, and temple service softens hearts on both sides of the veil. Everything in every temple testifies of Christ. Look for the miracles and build a personal temple culture.",
   ["Temple inscription “Holiness to the Lord, the House of the Lord” (no verse reported in recaps)"],
   ["While we are grateful our temples and everything in them are physically beautiful, let us celebrate and treasure even more the spiritual blessings temples bring.",
    "Covenants are not big or small. Please let us never speak of a temple as big or small, elaborate or plain.",
    "Dear brothers and sisters, come worship and rejoice with the Lord in the house of the Lord, in temple doctrine and in your personal temple culture."],
   "Come worship and rejoice in the house of the Lord; look for the miracles.",
   "What does my “personal temple culture” look like right now — and our family's?"),
 t("sat-am-2-runia", "sat-am", 2, "Sister Tamara W. Runia", "First Counselor, Young Women General Presidency", "The Sculpting of Our Souls",
   "sister-tamara-runia-october-2026-general-conference-sculpting-souls/",
   "Tempering, refining experiences are part of necessary mortal growth — “all these things shall give thee experience.” The gospel isn't an umbrella that keeps the rain off; it's the solid rock we stand on during the storm. A godlike life is carved from the very things that make it hard, and God waits for our invitation before He really goes to work. She shared the sudden death of her son, a young father.",
   ["Doctrine and Covenants 122:7", "Helaman 5:12"],
   ["God's love has moved me from questions that begin with ‘why’ to reflections that begin, ‘I know that God loves me, so what is supposed to be happening here?’",
    "Christ's work in your life and His love for you are bigger than your present story. And He can fix what feels badly broken.",
    "God is shaping us into something only He knows we can become."],
   "Invite God to do His sculpting work. He can fix what feels badly broken.",
   "Where am I still asking “why” instead of “what is supposed to be happening here?”"),
 t("sat-am-3-causse", "sat-am", 3, "Elder Gérald Caussé", "Quorum of the Twelve Apostles", "The Gift of Testimony",
   "elder-gerald-causse-october-2026-general-conference-gift-of-testimony/",
   "Apostles are special witnesses of Christ, but the privilege of bearing witness extends to all disciples and is a way to keep our baptismal covenant. Testimony is deeply personal and grows through faith, seeking, living the gospel and the Holy Ghost. A sincere, humble testimony has power to change both giver and receiver. Look for daily opportunities — at home, at church, ministering, online and in everyday conversations.",
   ["Doctrine and Covenants 107:23", "Mosiah 18:9"],
   ["Bearing witness is a foundational responsibility of discipleship.",
    "Your testimony may be different from mine or that of other family members or fellow Saints. Please trust it, nurture it and bear it, because it is uniquely yours.",
    "There is great power in a sincere, humble and heartfelt testimony. It need not be long, eloquent or dramatic — it only needs to be true."],
   "Look for opportunities each day to bear witness of Jesus Christ, even briefly.",
   "When did I last simply and briefly testify of Christ at home?"),
 t("sat-am-4-sikahema", "sat-am", 4, "Elder Vaiangina Sikahema", "General Authority Seventy", "Prophets, Seers and Revelators",
   "elder-sikahema-october-2026-general-conference-prophets-seers-revelators/",
   "In 1947 his grandparents sailed across the Tongan islands to hear a visiting apostle; their infant son died on the journey, yet they buried him and continued. People through the ages have yearned for prophetic voices. Today we can see and hear prophets on our phones, yet many take them for granted. What a blessing to live when apostles and prophets are on the earth.",
   ["Doctrine and Covenants 90:5"],
   ["What a blessing it is to live in a time when apostles and prophets are on the earth.",
    "I suspect the Lord knew that even when we would have these devices [cellphones] to easily see and hear His anointed servants, many of us would still take them for granted.",
    "Let us not be guilty of holding the oracles of God ‘as a light thing.’"],
   "Don't hold the oracles of God as a light thing; give prophetic words the effort earlier Saints sacrificed for.",
   "Do I treat conference as background noise or as an appointment?"),
 t("sat-am-5-hathaway", "sat-am", 5, "Elder Kevin J. Hathaway", "General Authority Seventy", "Jesus Christ Is the Great Deliverer",
   "elder-kevin-j-hathaway-october-2026-general-conference-jesus-christ-deliverer/",
   "Scripture shows a pattern of divine deliverance: opposition that raises heart-rending questions; sincere seeking through prayer, fasting and scripture study; assurance that the Savior visits us in our afflictions as we keep covenants; enabling grace that strengthens us without removing all pain; and deliverance in His time and way. When it feels too late, remember Jairus.",
   ["Mark 5:36", "Luke 8:50 (“Be not afraid, only believe”)"],
   ["With perfect understanding and infinite power, He can deliver the righteous from all things, forever.",
    "The Lord is not delayed, distracted or derelict in His deliverance. He has not forgotten you.",
    "Some miracles are immediate, some come after long waiting, and some await the Resurrection."],
   "Trust that in His time and way, Jesus Christ will deliver you.",
   "What am I waiting on the Lord for right now, and what growth might the waiting be producing?"),
 t("sat-am-6-soares", "sat-am", 6, "Elder Ulisses Soares", "Quorum of the Twelve Apostles", "A Higher and Holier Fast",
   "elder-ulisses-soares-october-2026-general-conference-higher-and-holier-fast/",
   "The Lord's call to fast echoes Isaiah, with promised blessings of light after darkness, healing, and assurance that He is near. A sincere fast is accompanied by earnest, intentional prayer, and finds its highest expression in Jesus Christ. Fasting is an act of worship that refines discipleship and prepares us for revelation; fast offerings help “let the oppressed go free.”",
   ["Isaiah 58:6"],
   ["A sincere and faithful fast is accompanied by earnest and intentional prayer.",
    "[Fasting and prayer] may not remove every burden from our path, but they draw heaven near and endow us with divine power to overcome or endure whatever circumstances we may face.",
    "I invite you to prayerfully ponder Isaiah's teachings and more intentionally embrace the divine purpose of the law of the fast in a higher and holier way as part of our worship."],
   "Ponder Isaiah's teachings and embrace the law of the fast more intentionally as worship.",
   "Is my fast a skipped meal or an act of worship with a clear purpose?"),
 t("sat-am-7-douglas", "sat-am", 7, "Bishop Sean Douglas", "Second Counselor, Presiding Bishopric", "The Hour of Your Mission Is Come",
   "bishop-sean-douglas-october-2026-general-conference-hour-your-mission-come/",
   "Missionaries are divinely commissioned to invite God's children to come unto Christ; they are both messengers and living examples. Elder Merlin Sanchez's story showed how a mission builds lifelong discipleship. Worthy, able young men have a priesthood responsibility to serve; young women are invited to prayerfully consider serving. Missionaries of all ages find joy in the work.",
   ["No specific verses reported in recaps"],
   ["Make no mistake — you are doing the most important work you could be doing.",
    "To all the rising generation of the Church, I invite you to place serving a full-time mission high on your list.",
    "There is still plenty of room and a special place reserved for each of you. We need you. ‘Come join the ranks.’"],
   "Rising generation: place a full-time mission high on your list. Senior missionaries are welcome too.",
   "What did the Spirit highlight for me in this talk? What one invitation will I act on this week?"),
 t("sat-am-8-christofferson", "sat-am", 8, "President D. Todd Christofferson", "Second Counselor in the First Presidency", "O Be Wise",
   "president-d-todd-christofferson-october-2026-general-conference-gambling/",
   "Gambling has exploded, made continuous and private by smartphones, and disproportionately affects youth and young adults. Beyond lost money, it displaces saving, increases debt and brings family and social costs. Gambling is morally wrong — built on desiring something for nothing — and crowds out things of value. He pled for us to live on a higher plane and use saved time and resources for good.",
   ["Jacob 6:12 (“O be wise; what can I say more?”)", "Doctrine and Covenants 58:27"],
   ["For us as Latter-day Saints, overarching all other concerns is the fact that gambling is morally wrong. Gambling is built on the desire to obtain something for nothing.",
    "Today, I am pleading with all of us to live life on a higher plane.",
    "Work leads to prosperous, just and equitable societies. Gambling, even for fun, leads in the opposite direction."],
   "Refrain from gambling and use the time and resources saved for doing good.",
   "What “good cause” could absorb time I currently spend on idle pursuits?"),
 t("sat-pm-1-renlund", "sat-pm", 1, "Elder Dale G. Renlund", "Quorum of the Twelve Apostles", "How Long Will It Be Ere They Believe Me",
   "elder-dale-g-renlund-october-2026-general-conference-trust-savior/",
   "A heart-transplant patient who survived against overwhelming odds later complained about cold oatmeal. Like him, and like ancient Israel, we can fixate on the here and now and lose sight of the bigger picture and God's promises. God invites us to trust Him; Christ has overcome the world, and His power to save is infinite and intimate.",
   ["Numbers 14:11", "cf. John 16:33"],
   ["God invites us to trust Him and His promises.",
    "Jesus overcame the world; we do not have to do so ourselves. When our faith is centered on Jesus Christ, He promises spiritual peace no matter our circumstances.",
    "As we reflect on the great things the Lord has already done and remember His goodness and mercy, we are better positioned to grasp the bigger picture and to rely on His promises to us. We can trust Him."],
   "Remember what the Lord has already done and rely on His promises personally.",
   "What is my “cold oatmeal” — the small frustration crowding out a miracle?"),
 t("sat-pm-2-farnes", "sat-pm", 2, "President Timothy L. Farnes", "Young Men General President", "Divine Appointments",
   "president-farnes-october-2026-general-conference-divine-appointments/",
   "As covenant followers of Jesus Christ we minister with compassion to whomever God places in our path, because that's what the Savior did. Taking His name means seeing as He sees, feeling as He feels and doing as He would do, so people experience something of Christ in us. God places people in our path — “divine appointments.”",
   ["Sacrament covenant to take Christ's name (no specific verse reported in recaps)"],
   ["As covenant followers of Jesus Christ, we minister with compassion to whomever God places in our path.",
    "When someone encounters us, they should experience something of Jesus Christ — His kindness, His patience, His hope, His love, His compassion.",
    "Let us pray every day for eyes to see the divine appointments God places before us. Let us put compassion into action and minister to the person in front of us. It's what Jesus did."],
   "Pray daily for eyes to see divine appointments and minister to the person in front of you.",
   "Who did God place in my path this week that I walked past?"),
 t("sat-pm-3-chigbundu", "sat-pm", 3, "Elder Christian C. Chigbundu", "General Authority Seventy", "Spiritual Immunity",
   "elder-christian-chigbundu-october-2026-general-conference-spiritual-immunity/",
   "These are troubled times, but we need not fear. Build spiritual immunity through four small and simple things: daily meaningful scripture study; prayer; the sacrament, remembered throughout the week; and covenants, including temple worship. Together they are the armor of God.",
   ["Alludes to the “armor of God” and “small and simple” things (no verse cited in recaps)"],
   ["As we build our spiritual immunity, we develop the strength and courage to withstand the challenges of life.",
    "Remember that trials may come, yet, as we worship in the temple and remember our covenants, we receive personal direction from the Lord that will guide us along the covenant path.",
    "I invite you to always remember scriptures, prayers, sacrament and covenants. While they may seem small and simple, they are truly the armor of God."],
   "Always remember scriptures, prayers, sacrament and covenants.",
   "Which of the four (scriptures, prayer, sacrament, covenants) is weakest in my week?"),
 t("sat-pm-4-giuffra", "sat-pm", 4, "Elder Patricio M. Giuffra", "General Authority Seventy", "Trusting the Lord Through Tithes and Offerings",
   "elder-patricio-giuffra-october-2026-general-conference-tithing-offerings/",
   "As a missionary in Chile he taught a 70-year-old woman who cleaned houses to pay rent and said she couldn't pay tithing. His mission president said he was “no one to deny this sister the blessings of the law of tithing.” She prayed for help, was baptized and paid tithing faithfully. The Lord keeps His promises; the windows of heaven open according to obedience.",
   ["Alludes to the “windows of heaven” promise (Malachi 3:10)"],
   ["Commandments are given to draw us closer to the Savior, to protect us and to help us remain free from sin and many of the challenges the world presents.",
    "Even when we do not understand the purpose of our trials, we can have the assurance that the Lord knows our circumstances, honors our obedience and fulfills His promises in His own time and way.",
    "I testify that the law of tithing is a law of faith. As we obey it, we demonstrate our trust in the Lord and allow Him to work miracles in our lives, often in ways we do not expect."],
   "Trust the Lord's promises; don't withhold the blessings of a commandment from others by lowering the standard.",
   "Where am I tempted to “make an exception” for someone and withhold the blessing of a commandment?"),
 t("sat-pm-5-morgan", "sat-pm", 5, "Elder Jeremiah J. Morgan", "General Authority Seventy", "The Infinite Power of God in Our Covenants",
   "elder-jeremiah-morgan-october-2026-general-conference-infinite-power-of-god-in-covenants/",
   "His mother read the Book of Mormon aloud to him every day, whether he listened or not; as a young man he came to know this is the Lord's Church and was baptized at 18. Covenants that came before him reached after him. Covenant faithfulness doesn't override a child's agency, but it has a generational impact. Don't lose hope in loved ones who have wandered.",
   ["Echoes Hebrews 12:2 (“author and finisher”)"],
   ["No time or effort is ever wasted in reading the Book of Mormon. Not for you, not for your children, not for your family, not for anyone.",
    "Covenants with God are filled with incalculable power.",
    "Don't ever give up. Your story, your family's story, is not all written. God is the author and the finisher of it."],
   "Keep reading the Book of Mormon with your family; never give up.",
   "Whose covenants have reached after me?"),
 t("sat-pm-6-fale", "sat-pm", 6, "Elder Hutch U. Fale", "General Authority Seventy", "I Am a Child of God",
   "elder-hutch-fale-october-2026-general-conference-i-am-a-child-of-god/",
   "“I am a child of God, and He loves me” is true for everyone. Understanding the Father's love and our identity prevents deception, gives purpose to mortality and brings power, peace and comfort. Beware the lie that we can be saved regardless of sin. Knowing His love helps us reject divisive labels and know it's not too late to turn to Christ. Families, despite imperfections, often teach us God's love.",
   ["Luke 15 (prodigal son, lost sheep)"],
   ["Understanding our Father's love and our true identity as His children is essential for our daily and eternal happiness. It prevents deception and gives purpose to this mortal life.",
    "From the prodigal son to leaving the 99 sheep to find the one, our Father's message, through His Son, has always been that there is still yet time, if we turn to Christ today.",
    "It is often through families, despite all their imperfections, that Our Father teaches us about His love."],
   "Turn to Christ today — there is still time.",
   "Which labels do I accept above “child of God”?"),
 t("sat-pm-7-kearon", "sat-pm", 7, "Elder Patrick Kearon", "Quorum of the Twelve Apostles", "Jesus Lives to Lift",
   "elder-patrick-kearon-october-2026-general-conference-jesus-lives-lift/",
   "Drawing on flying gliders as a teenager, he taught spiritual “lift” and “sink.” Lift can't be seen but can be felt through the Holy Spirit, drawing us toward Christ. Seek the feelings of the Holy Ghost and join those who are climbing; watch for subtle signs of sink and turn away decisively; and when you find lift, show others where and how to rise.",
   ["The Savior “lifted up” on the cross; His followers “shall be lifted up at the last day” (no verse cited in recaps)"],
   ["At the heart of our faith is the glorious truth that we have an adoring Father in Heaven, whose Son, our Savior, loves to lift.",
    "We can learn to live in spiritual lift. And when we sink, our gentle Savior is there to lift us up as we turn to Him.",
    "Your Savior is your lift. He is your ever-rising air. There is no limit to how high you can climb with Him. Jesus Christ lives to lift."],
   "Seek lift, turn decisively away from sink, and show others where to rise.",
   "What are the subtle signs of “sink” in my week?"),
 t("sat-pm-8-dunn", "sat-pm", 8, "Elder Michael A. Dunn", "General Authority Seventy", "The 90 and 10",
   "elder-dunn-october-2026-general-conference-90-and-9/",
   "Comparing mortality to an ultramarathon he was ready to quit long before the finish, he taught that races can devolve from running to walking to shuffling. The Savior bears our griefs and magnifies our smallest offerings. Giving 90% of a spiritual journey may take all we have; the Savior extends His hand for the final 10%.",
   ["Hymn “Lord, I Would Follow Thee” (Hymns, no. 220)"],
   ["The Redeemer rescues not by shortening our course, but by helping us lengthen our stride.",
    "Don't confuse the perceived invisibility of the Lord's hand with the inveterate nature of the Lord's heart.",
    "Peace will come even when hoped-for outcomes do not."],
   "Give what you can; trust the Savior for the final 10%.",
   "Where am I shuffling right now, and what would “lengthening my stride” look like?"),
 t("sat-pm-9-eyring", "sat-pm", 9, "Elder Matthew J. Eyring", "General Authority Seventy", "Comfort From the Holy Ghost",
   "elder-matthew-j-eyring-october-2026-general-conference-comfort-holy-ghost/",
   "Every child of God faces challenges impossible to overcome without the Savior. Handing burdens to the Lord lets us see His promise fulfilled: draw near to Him and He will draw near. In increasing turbulence, true comfort will become scarcer. The Savior's peace is made manifest through the comforting power of the Holy Ghost.",
   ["Doctrine and Covenants 88:63"],
   ["In a world of increasing temporal and spiritual turbulence, true sources of comfort will become more scarce. … There is hope in Jesus Christ.",
    "Someday we will more fully realize how generous and kind the Lord has been to each of us.",
    "Living worthy of the constant companionship of the Holy Ghost should be one of our highest priorities."],
   "Make living worthy of the Holy Ghost's constant companionship a top priority.",
   "Where do I turn first for comfort — the Holy Ghost or something else?"),
 t("sat-pm-10-rasband", "sat-pm", 10, "Elder Ronald A. Rasband", "Quorum of the Twelve Apostles", "Love Like Jesus",
   "elder-ronald-a-rasband-october-2026-general-conference-love-like-jesus-wayward-souls/",
   "Many hearts ache for loved ones who have turned away. By divine design, each person must choose for themselves to follow Christ. Turn your despair over to Jesus Christ — we cannot change their hearts, but He can. Love is the centerpiece of His gospel. Let go of guilt; Christ has already paid for the choices of those we grieve for. Keep loving, praying, and never give up.",
   ["No specific verses reported in recaps"],
   ["I ask you to turn over to Jesus Christ your despair for those wayward souls. We cannot change their hearts, but He can; He is a God of miracles.",
    "Love is not stepping back or sanctioning others' decisions and actions. Love is being interested in their lives, their successes and their challenges. Love is being there with arms outstretched and a cheerful countenance.",
    "He knows them. He knows their hearts; He loves them. He gave His very life to bring them home, all the way home."],
   "Turn your despair over to Christ; let go of guilt; keep loving and praying.",
   "Whom am I carrying guilt or despair for that I need to give to Christ?"),
 t("sun-am-1-eyring", "sun-am", 1, "President Henry B. Eyring", "First Counselor in the First Presidency", "Fear Not, I Am With Thee",
   "https://www.thechurchnews.com/general-conference/2026/10/04/president-henry-b-eyring-october-2026-general-conference-fear-not-i-am-with-thee/",
   "President Eyring spoke about helping give the Lord's comfort to others. The Lord's promised comfort in Isaiah 41 and the hymn “How Firm a Foundation” (“Hymns,” No. 85) will become more important and more precious. Mortal tests are hard because we must grow in spiritual cleanliness and stature to live in God's presence; Heavenly Father gave us a Savior and the power to choose by faith to keep commandments, repent and come unto Him. The promise is not for the removal of challenges. The Lord sends faithful disciples to help Him keep His promise to succor others; we are invited to join Him in that work.",
   ["Isaiah 41:10", "Hymn “How Firm a Foundation” (Hymns, no. 85)"],
   ["It is because He knows that we must grow in spiritual cleanliness and stature to be able to live in His presence. To make that possible, Heavenly Father gave us a Savior and the power to choose for ourselves by faith to keep His commandments and to repent and to come unto Him.",
    "The Lord sends faithful disciples to help Him keep his promise to succor others in their distress.",
    "We shed tears of joy and take courage whenever we hear the words, ‘Fear not, I am with thee,’ and we are touched that He offers us the trust of helping and loving others."],
   "Join the Lord in keeping His promise — help Him comfort and succor those in distress.",
   "Whom is the Lord inviting me to comfort for Him today?"),
 t("sun-am-2-chibota", "sun-am", 2, "President Rosemary K. Chibota", "Primary General President", "A Child of God",
   "https://www.thechurchnews.com/general-conference/2026/10/04/president-rosemary-chibota-october-2026-general-conference-a-child-of-god/",
   "Primary General President Rosemary K. Chibota spoke about seeing each other as children of God. The Southern African greeting “Sawubona” means “I see you” — an acknowledgment of another person’s worth and humanity. Jesus Christ saw people as beloved sons and daughters of God rather than by labels. The world invites focus on labels, but labels never fully capture who we truly are; eternal identity matters more. Whatever labels weigh heavily, Jesus Christ’s grace is sufficient to lift above every label and limitation. She invited disciples this week to learn the name of someone who may feel unseen, pray to see others as Heavenly Father sees them, and replace worldly labels with the eternal truths: child of God, child of the covenant, disciple of Jesus Christ.",
   ["No specific verses reported in recaps"],
   ["The world invites us to focus on labels rather than eternal identity. However, labels can never fully capture who we truly are",
    "When we ask Heavenly Father to help us see others, He guides us to those who feel unseen.",
    "When we see one another through the Savior’s eyes, hearts change, relationships deepen and faith grows."],
   "Pray to see others as Heavenly Father sees them; learn the name of someone who may feel unseen.",
   "Whom am I labeling instead of seeing as a child of God?"),
 t("sun-am-3-andersen", "sun-am", 3, "Elder Neil L. Andersen", "Quorum of the Twelve Apostles", "Courage Born of Our Faith in Jesus Christ",
   "https://www.thechurchnews.com/general-conference/2026/10/04/elder-andersen-october-2026-general-conference-courage-born-of-faith/",
   "Elder Neil L. Andersen of the Quorum of the Twelve Apostles spoke about spiritual courage being born of faith in Jesus Christ. Faith and courage are hallmarks of Jesus Christ’s disciples. As we choose faith in Christ, He blesses us with courage to choose the right even in difficult situations, and as we manifest that courage, our faith strengthens. Discipleship always requires spiritual courage; courage is born of faith in Jesus Christ. Being His true disciple — overcoming the world, keeping commandments, trusting Him and His promises — is not a casual pursuit. Spiritual courage is the triumph over obstacles, doubt, and fear in choosing the right. With the world in constant commotion, disciples need stillness to nourish their faith in Christ. Even when troubled on every side, they are not in despair when hope is alive in Christ (2 Corinthians 4:8). Faith in Him brings spiritual courage to minister, keep commandments, speak openly of the Savior, be guided by the Holy Ghost, repent, and receive forgiveness.",
   ["2 Corinthians 4:8"],
   ["As we choose faith in Christ, He blesses us with the courage, sometimes in very difficult situations, to choose the right, and as we manifest our courage to choose the right, our faith in Christ strengthens.",
    "It is our faith in Christ that gives us the spiritual courage to speak openly to others of our Savior, make covenants in the house of the Lord, repent and receive forgiveness, follow living prophets and be guided by the quiet impressions of the Holy Ghost.",
    "I promise you that as you strengthen your faith in Jesus Christ by believing and following Him and keeping His commandments, your answers will come, your spiritual power will increase, and your courage in following Christ will define your eternal soul."],
   "Strengthen your faith in Jesus Christ by believing, following Him, and keeping His commandments.",
   "Where do I need spiritual courage right now — and how will I strengthen my faith in Christ to receive it?"),
 t("sun-am-4-fantone", "sun-am", 4, "Elder James G.O. Fantone", "General Authority Seventy", "Take Upon Us His Name",
   "https://www.thechurchnews.com/general-conference/2026/10/04/elder-james-fantone-october-2026-general-conference-take-upon-us-his-name/",
   "Elder James G.O. Fantone, General Authority Seventy, spoke about taking upon the name of Jesus Christ. Jesus Christ invites all to take upon us His name and become more like Him by making and keeping covenants and serving others. Book of Mormon prophets taught that following baptism, taking upon oneself the name of Jesus Christ requires a lifelong commitment to serve Him. Latter-day Saints can learn from righteous, charitable examples of family members and full-time missionaries who demonstrate courageous service. When we genuinely take upon ourselves His name by losing ourselves in the service of others, something miraculous happens — a mighty change of heart that leads to true conversion. Taking upon the Savior’s name means more than a badge of religious affiliation; His invitation is to take His name by covenant and serve Him with all heart, might, mind and strength — by lifting, loving and serving others. As we lose our lives in His service, we will find Him, and we will find ourselves.",
   ["Alma the Younger on a “mighty change” of heart (no specific verse cited in recaps)"],
   ["The Savior’s invitation is not merely for us to add His name to our name like a badge of religious affiliation.",
    "Taking upon us His name requires a lifelong determination to serve Him.",
    "When we genuinely take upon ourselves the name of Jesus Christ by losing ourselves in the service of others, something miraculous happens."],
   "Take upon the name of Jesus Christ by covenant — lose yourself in serving others with all your heart, might, mind and strength.",
   "Where am I merely wearing His name as a badge, instead of serving Him by lifting and loving others?"),
 t("sun-am-5-dube", "sun-am", 5, "Elder Edward Dube", "Presidency of the Seventy", "Come Unto Christ",
   "https://www.thechurchnews.com/general-conference/2026/10/04/elder-edward-dube-october-2026-general-conference-come-unto-christ/",
   "Elder Edward Dube of the Presidency of the Seventy spoke about coming unto Christ. Moroni’s invitation — “Come unto Christ and be perfected in him … deny yourselves of all ungodliness” (Moroni 10:32) — holds three key truths: come (an action; choose to move from our current place to a better place), deny yourselves (surrender; let go of what holds us back), and be perfected in Him (come as we are with a willing heart; He will give us a new heart). People do not need to be perfect to come unto Christ — “We come to Christ to be perfected.” As a young missionary in 1987, he saw a mission-office gate sign reading “Trespassers will be prosecuted”; President Dallin H. Oaks asked that it be removed to avoid any impression of exclusion. The adversary wants to hang that sign on the gate of our heart — addiction, doubt, pride, pain, grief, guilt, materialism — telling us we are unworthy to come unto Christ. Elder Dube invited all to come unto Christ through faith in Him and His Atonement.",
   ["Moroni 10:32"],
   ["We invite all to come unto Christ through faith in Him and His Atonement.",
    "[Jesus Christ’s] suffering and atoning sacrifice show us how completely devoted He is to all of us. He invites us to come unto Him.",
    "We do not need to perfect ourselves to come to Christ. We come to Christ to be perfected."],
   "Come unto Christ through faith in Him and His Atonement — you do not need to perfect yourself first.",
   "What “trespassers” sign has the adversary hung on the gate of my heart that I need to let go of?"),
 t("sun-am-6-cook", "sun-am", 6, "Elder Quentin L. Cook", "Quorum of the Twelve Apostles", "Integrity and Virtue Lead to Happiness",
   "https://www.thechurchnews.com/general-conference/2026/10/04/elder-quentin-l-cook-october-2026-general-conference-integrity-virtue-lead-happiness/",
   "Elder Quentin L. Cook of the Quorum of the Twelve Apostles spoke about integrity, virtue and happiness. As a new missionary, President David O. McKay passed a building with a stone above the doorway inscribed “What e’er thou art, act well thy part.” In Heavenly Father’s plan, integrity, virtue and happiness are intrinsically linked — true happiness is the outcome of integrity and virtue. That relationship is less well understood today; the founders of the United States emphasized life, liberty and happiness based on living a virtuous life. The Lord wants us to experience the joy of a virtuous life and richly rewards those who make sacrifices in His name. Covenant keepers are expected to live lives of virtue and integrity; the ultimate reward is the constant companionship of the Holy Ghost. Part of integrity is acknowledging faults to the Lord and repenting. When repentance is a constant day-to-day part of our lives, we can approach the Lord with integrity and receive His saving blessings. Integrity, virtue and ongoing repentance are the answer to today’s challenges.",
   ["Alludes to Doctrine and Covenants 121:45 (“Let virtue garnish thy thoughts unceasingly”) — Liberty Jail guidance referenced in recaps"],
   ["The virtuous Christlike life necessary to sustain us and propel us along the covenant path has never been more important or challenging.",
    "In the Father’s plan, integrity, virtue and happiness are intrinsically linked.",
    "Integrity, virtue and on-going repentance are the answer in a world where coarse language and serious challenges are so prevalent."],
   "Live with integrity and virtue; make repentance a constant day-to-day part of your life.",
   "Where do I need more integrity and virtue so the Holy Ghost can be my constant companion?"),
 t("sun-am-7-kyungu", "sun-am", 7, "Elder Alfred Kyungu", "General Authority Seventy", "Using the Language of Peacemakers",
   "https://www.thechurchnews.com/general-conference/2026/10/04/elder-alfred-kyungu-october-2026-general-conference-using-language-of-peacemakers/",
   "Elder Alfred Kyungu, General Authority Seventy, spoke about using the language of peacemakers. The invitation to forgo contention by using the language of peacemakers comes from the living Prophet and is a call to discipleship as individuals follow Jesus Christ. It is a spiritual exercise to identify language and expressions to forgo and replace them with words and phrases that bring peace. Remove words that damage relationships — such as “You are useless,” “Just stop talking” or “What is wrong with you?” — which weaken love, diminish respect and damage relationships. Rather than words that escalate anger, disappointment and frustration, choose words that encourage understanding and peace and that strengthen confidence and preserve relationships — such as “Thank you,” “I’m sorry” and “I forgive you.” The true doctrine of Christ has power to change language. He invited Saints to repent of harsh language that has offended friends, leaders, family members and colleagues; to pray for peaceful communication regardless of differences of opinion; and to use language that uplifts, edifies, comforts and brings people together.",
   ["No specific verses reported in recaps"],
   ["It is a spiritual exercise to identify the language and expressions we need to forgo and then replace them with words and phrases that bring peace wherever we are and at all times.",
    "Rather than choosing words and language that escalate feelings of anger, disappointment and frustration, let us use words that encourage understanding and peace. We must choose language that strengthens confidence and preserves relationships.",
    "Let us repent of the harsh language and expressions that have offended our friends, leaders, family members and colleagues. Let us pray for peaceful communication among us, regardless of the difference in our opinions. Let us use the language that uplifts, edifies, comforts and brings people together."],
   "Repent of harsh language; choose peacemaking words that uplift, edify and preserve relationships.",
   "What harsh words do I need to forgo this week — and what peacemaking words will replace them?"),
 t("sun-am-8-schmeil", "sun-am", 8, "Elder Ciro Schmeil", "General Authority Seventy", "Consider Your Ways, and From This Day Will I Bless You",
   "https://www.thechurchnews.com/general-conference/2026/10/04/elder-ciro-schmeil-october-2026-general-conference-covenants-jesus-christ/",
   "Elder Ciro Schmeil, General Authority Seventy, spoke about making covenants with God. God did not leave His children alone on the journey to return to Him — two divine helps are the Savior, Jesus Christ, and covenants. The Savior knows us individually and will help us if we seek Him; we show our faith in Christ by making and keeping covenants with God. Through covenants we become yoked with the Savior and our burdens become lighter. Baptism is the first covenant and is renewed each week by partaking of the sacrament, which is essential to have the Spirit and strength to continue on the covenant path. In Haggai, the Israelites were commanded to rebuild the temple, did not make it a priority, were rebuked, then considered their ways and repented; the Lord said, “from this day will I bless you” (Haggai 2:19). Heavenly Father is not asking us to physically build the temple, but to build a strong relationship with Him and His Son through our covenants; He will magnify our efforts as we make the proper adjustments to make and keep covenants with Him.",
   ["Haggai 2:19"],
   ["It is through covenants that we become yoked with the Savior, Jesus Christ, and our burdens become lighter.",
    "May we also consider our ways. Heavenly Father is not asking us to physically build the temple, but He is asking us to build a strong relationship with Him and His Son, Jesus Christ, through our covenants.",
    "I know that God keeps His promises. I have seen it in my life. He gave me spiritual and physical strength when I needed it most."],
   "Consider your ways; build a strong relationship with Heavenly Father and Jesus Christ through making and keeping covenants.",
   "What “proper adjustments” do I need to make so I can better make and keep my covenants?"),
 t("sun-am-9-oaks", "sun-am", 9, "President Dallin H. Oaks", "President of the Church", "The Gospel of Jesus Christ Is for All",
   "https://www.thechurchnews.com/general-conference/2026/10/04/president-oaks-october-2026-general-conference-gospel-of-jesus-christ-for-all/",
   "President Dallin H. Oaks, President of the Church, closed the Sunday morning session speaking about overcoming through the Savior. Members both obey Amaleki’s invitation and invite all others to “come unto Christ” (Omni 1:26). As President, he prays for what Heavenly Father wants for each of us — to be active members of the Church of Jesus Christ, proceeding forward on the covenant path into the eternities; we need one another’s prayers. Each person is a work in progress with personal trials; whatever present or future concerns or struggles we face, the way to overcome them is to get closer to the Savior. Challenges of mortality provide opportunities to develop faith. Strong faith requires more than strong desire — it means daily trying, one step at a time, with prayer and scriptural learning. Reconciling conflicts between science and religion can take time and may build faith and humility; never let secular learning limit spiritual horizons. If sins are to be forgiven through His Atonement, we must comply with the conditions He has prescribed, including faith, repentance and baptism. He testified the gospel of Jesus Christ is for all and invited all to come unto Christ and help others do the same.",
   ["Omni 1:26"],
   ["I pray for what our Heavenly Father wants for each of us — to be active members of the Church of Jesus Christ, proceeding forward on the covenant path into the eternities.",
    "We all have present or future concerns or struggles we are trying to overcome. ... Whatever they are, the way to overcome them is to get closer to our Savior, Jesus Christ.",
    "The Lord will eventually cause the inspired teachings He has given to His children in various nations to be brought forth for the benefit of all people."],
   "Get closer to the Savior — come unto Christ, and help others do the same. The gospel of Jesus Christ is for all.",
   "What concern or struggle am I trying to overcome on my own instead of getting closer to Christ?"),
 t("sun-pm-1-uchtdorf", "sun-pm", 1, "President Dieter F. Uchtdorf", "Acting President of the Quorum of the Twelve Apostles", "Christ-centered Unity",
   "https://www.thechurchnews.com/general-conference/2026/10/04/president-uchtdorf-october-2026-general-conference-christ-centered-unity/",
   "Baptism, while an individual ordinance, is also a unifying one — it joins us to a worldwide community of Saints. Through baptism, we become not only covenant individuals but also part of a covenant people. The Savior brought people together and broke down divisions and walls; He continues to invite all to come unto Him. Satan seeks to divide, but the Savior's work of gathering is accelerating. Members are united by love for God and neighbor; they are one in Christ (Galatians 3:28). Wars and contentions between the Nephites and the Lamanites changed when Jesus Christ appeared, taught His gospel and established His Church; they became His covenant people. The closer people become to Jesus Christ, the closer they will become to each other. If we are not one, we are not His. Now is the time to unify. The sacrament is also a weekly unifying experience. Wherever you are, join the Christ-centered unity we are trying to build. The more united in Christ we are and the more we desire to build bridges instead of walls, the more our individual lives, families, communities and nations will experience God's presence and blessings.",
   ["Galatians 3:28"],
   ["When we join the Church of Jesus Christ, we say — humbly, gratefully, and with quiet confidence — that we want to follow our beloved Savior, Jesus Christ. And we want to walk that path together.",
    "In the Savior's Church, it is not our political views, culture or personal interests that unite us. It is our love for God and neighbor — God's children. It is our commitment to our covenants with Jesus Christ and to His restored gospel. We are 'one in Christ.'",
    "Jesus Christ has the power to change us — you and me — purify us and unite us. The closer we come to Him, the closer we will come to each other — and the closer we will come to the unity He wants for us."],
   "Join the Christ-centered unity; build bridges instead of walls; come closer to Christ and to each other.",
   "Where am I building walls instead of bridges — and how can I come closer to Christ so I come closer to others?"),
 t("sun-pm-2-spannaus", "sun-pm", 2, "Sister Andrea Muñoz Spannaus", "Second Counselor in the Young Women General Presidency", "God Is at Your Side",
   "https://www.thechurchnews.com/general-conference/2026/10/04/sister-andrea-munoz-spannaus-october-2026-general-conference-thirteenth-article-of-faith/",
   "Speaking to young women about accomplishing their crucial and important work on earth. As they look at their lives and what they want to achieve, Heavenly Father will show them the best way to make their righteous desires come true. The Lord knows where they are; He has their exact location and can guide them. He knows their dreams and gifts. Knowing everything about them does not make Him love them less. She shared seven helps and invited listeners to choose one to focus on over the next few weeks: (1) Partake of the sacrament with a humble heart; (2) Repent daily; (3) Study the scriptures with a desire to know God's character; (4) Study about ministering angels; (5) Go to bed early; (6) Limit cellphone use; (7) Seek friends who are striving to follow the Lord. The Lord has greater power than the adversary. Always put Him first and remain faithful to baptismal covenants. Angels can minister; the Father, Jesus Christ and the Holy Ghost are at your side. She invited study of the 13th article of faith and creating your own list of aspirations.",
   ["Articles of Faith 1:13"],
   ["Today I invite you to look at your life and what you want to achieve with enthusiasm and the certainty that your Father in Heaven will guide you on that journey and show you the best way to make the righteous desires of your heart come true.",
    "Dear young women, the Lord knows where you are; He has your exact location and can guide you. … He knows everything. And knowing everything about you does not make Him love you less.",
    "Always put Him first and remain faithful to the covenants you made at your baptism. Angels can minister to you. The Father, Jesus Christ and the Holy Ghost are at your side."],
   "Choose one of her seven helps to focus on; study the 13th article of faith and create your own list of aspirations; put the Lord first.",
   "Which one of her seven invitations will I focus on for the next few weeks?"),
 t("sun-pm-3-villanueva", "sun-pm", 3, "Elder Moisés Villanueva", "General Authority Seventy", "Prove Me Now Herewith",
   "https://www.thechurchnews.com/general-conference/2026/10/04/elder-moises-villanueva-october-2026-general-conference-prove-me-now-herewith/",
   "Speaking about the blessings the Lord promises to those who faithfully pay tithing. When his family was baptized into the Church, perhaps the change that required the greatest faith and sacrifice was paying a full tithe, and he is grateful his mother trusted the Lord's promises and lived the law of tithing despite difficult circumstances. Blessings he has received through faithful tithing include steady employment, good health, his home and temporal possessions being preserved, the ability to manage time and resources to get an education, the gift of gratitude, and learning to recognize the influence of the Holy Ghost in important decisions. These temporal and spiritual blessings are evidence that the Lord opens the windows of heaven (Malachi 3:10). God gives commandments because He wants us to receive His blessings; He knows each of us and our needs even before we ask.",
   ["Malachi 3:10"],
   ["By living the law of tithing, the Lord indeed opens the windows of heaven and pours out a blessing ‘that there shall not be room enough to receive it’ (Malachi 3:10).",
    "These blessings, both temporal and spiritual — and many others — are evidence that the Lord has indeed opened the windows of heaven and poured out His promised blessings in abundance.",
    "I bear my testimony that God is our loving Heavenly Father. He knows each of us and is aware of our needs even before we ask."],
   "Trust the Lord's promises and live the law of tithing faithfully, then watch for the temporal and spiritual blessings He pours out.",
   "What blessings — temporal or spiritual — have come into my life through paying tithing, and have I recognized them?"),
 t("sun-pm-4-bednar", "sun-pm", 4, "Elder David A. Bednar", "Quorum of the Twelve Apostles", "Sealed by the Holy Spirit of Promise",
   "https://www.thechurchnews.com/general-conference/2026/10/04/elder-david-bednar-october-2026-general-conference-sealed-holy-spirit-promise/",
   "Speaking about ordinances and covenants, with a focus on the sealing ordinance. A covenant is a solemn promise and enduring commitment between God and His children, received through sacred ordinances — holy acts performed by priesthood authority with spiritual purpose and eternal significance. Understanding ordinances helps us understand our covenants. Covenants and ordinances are spiritual credentials, and faithfulness keeps them valid to receive the promised blessings. The Holy Ghost is the Holy Spirit of Promise, who ratifies righteous acts as acceptable to God; during mortality that seal is conditional and can be forfeited through unrighteousness. The temple sealing of a man and a woman is a crowning covenant and ordinance; a spouse who violates covenants and does not repent loses the ratifying seal, while a faithful spouse who honors covenants and presses forward in faith remains worthy to receive the promised blessings.",
   ["The Holy Ghost as the “Holy Spirit of Promise” (no verse cited in recaps)"],
   ["For disciples of Jesus Christ, receiving priesthood ordinances and entering into sacred covenants are essential steps in the quest of a lifetime to align our hearts, minds and lives with God’s will.",
    "The covenants and ordinances of the Savior’s restored gospel are spiritual credentials that can open wide the heavenly windows of opportunity to receive in our lives divine purpose, direction and strength.",
    "Ultimately, all gospel ordinances and covenants must be sealed by the Holy Spirit of Promise."],
   "Honor your covenants and press forward in faith so your ordinances can be sealed by the Holy Spirit of Promise.",
   "Am I keeping my covenant “credentials” valid — and what would help me honor my temple covenants more faithfully?"),
 t("sun-pm-5-lebethoa", "sun-pm", 5, "Elder Thabo Lebethoa", "General Authority Seventy", "Jesus Christ Is the Light and Life of the World",
   "https://www.thechurchnews.com/general-conference/2026/10/04/elder-first-name-if-needed-lebethoa-october-2026-general-conference-jesus-christ-light-of-the-world/",
   "Speaking about how to receive more of the Savior’s light. The Savior said, “I am the light and the life of the world.” Through His Spirit He enlightens our minds, and His light is also revealed through His perfect life and teachings. Jesus Christ can bring light in our moments of darkness and restore hope where there is hopelessness; whatever concerns, challenges and struggles come in life, the answer is always Jesus Christ. To receive more of His light: first, increase faith in Him — trusting that He understands our daily difficulties and knows how to help us rise above them, because He has experienced all our pains, afflictions and infirmities; second, study the scriptures daily, especially the Book of Mormon — the method, timing and length of study matter less than the consistency and sincerity of our effort; third, practice repentance daily — a change of mind and a turning of the heart to God. He invited us to ponder the changes we need to make, which may include how we use our time, what we watch or listen to, and the language and tone we use with others. He testified that today can be a new day and tomorrow a better day for all who come unto Christ.",
   ["“I am the light and the life of the world” (no verse cited in recaps)", "“Come unto me, and I will give you rest” (no verse cited in recaps)"],
   ["Whatever concerns, challenges and struggles we may have in our lives, the answer is always Jesus Christ.",
    "Having faith in Jesus Christ means trusting that He understands our daily difficulties and knows how to help us rise above them, because He has experienced all our pains, afflictions and infirmities.",
    "I testify that today can be a new day, and tomorrow will be a better day, for all who come unto Jesus Christ and receive His light in their lives."],
   "Receive more of His light: increase faith in Christ, study the scriptures daily (especially the Book of Mormon), and practice daily repentance.",
   "What change — in how I use my time, what I watch or listen to, or how I speak to others — would let more of the Savior’s light into my life?"),
 t("sun-pm-6-sinclair", "sun-pm", 6, "Elder Paul H. Sinclair", "General Authority Seventy", "Quick to Help, Slow to Judge",
   "https://www.thechurchnews.com/general-conference/2026/10/04/elder-paul-h-sinclair-october-2026-general-conference-quick-to-help-slow-to-judge/",
   "Speaking about helping more and judging less. In the Gospel of John, Jesus Christ ministers to the Samaritan woman at the well. She may have endured much judgment because of her history of broken relationships and her circumstances at the time, but no one then or now knew the full truth of her situation. In contrast, Christ knew everything about her and offered her living water. He spoke to her with dignity, listened earnestly to her questions, answered with teaching, did not hold her hostage to her history, and trusted her with truth. Every day, missionaries meet people at modern-day wells around the world, finding, teaching, baptizing and confirming those who may fear judgment but need help. Disciples of Jesus Christ are invited to reorient their souls to help friends and new members in more Christlike ways, looking not only to a person's past but to their possible. Helping people rather than judging them, one by one in small and simple ways, prepares the world for the Second Coming.",
   ["The Samaritan woman at the well, Gospel of John (no verse cited in recaps)"],
   ["He spoke to the woman with dignity, not shame. He earnestly listened to her questions and responded with teaching, not ridicule. He did not hold her hostage to her history. He trusted her with truth.",
    "Jesus Christ reminds us that to help people transform their lives; we must look not only to ‘their past’ — we must look to ‘their possible.’",
    "Being quick to help and slow to judge is a simple and deeply encouraging way for each of us to be more holy, to be more like our Savior, to be His true disciples."],
   "Be quick to help and slow to judge — look to a person's possible, not only their past, especially friends and new members.",
   "Whom am I holding hostage to their history — and how could I help them instead of judging them?"),
 t("sun-pm-7-stevenson", "sun-pm", 7, "Elder Gary E. Stevenson", "Quorum of the Twelve Apostles", "Fruit To Make One Happy",
   "https://www.thechurchnews.com/general-conference/2026/10/04/elder-gary-stevenson-october-2026-general-conference-fruit-of-gospel/",
   "Speaking especially to children of Primary age about the fruits of the gospel. Like a favorite fruit, gospel truths become sweet to us as we live them, bringing happiness and joy. He shared three fruits he loves: first, we are children of a loving Heavenly Father, our most important identity, which makes us stronger and kinder to others; second, the plan of happiness, with the Atonement of Jesus Christ at its center, so we can repent, be forgiven and progress; and third, the gift of the Holy Ghost, a member of the Godhead who warns, comforts and testifies. He invited listeners to love, share and invite, with words and actions.",
   [],
   ["This knowledge makes us stronger. This knowledge also makes us kinder to others, knowing that everyone around us is our brother or sister.",
    "Your Heavenly Father and His Son, Jesus Christ, know you and love you. Even though you are young, you are an important part of Their work",
    "Consider how your family, friends and loved ones will be blessed to partake of the fruit that blesses you."],
   "Love, share and invite — with words and actions — so others can taste the fruit that blesses you.",
   "Which gospel truth has become sweetest to me as I've lived it — and whom could I invite to taste it?"),
 t("sun-pm-8-reid", "sun-pm", 8, "Brother Gabriel W. Reid", "Second Counselor in the Sunday School General Presidency", "You Are Good Enough To Teach",
   "https://www.thechurchnews.com/general-conference/2026/10/04/brother-reid-october-2026-general-conference-you-are-good-enough-to-teach/",
   "Speaking about teaching in the Church. The Lord invites all to teach His gospel, and wherever we teach — in classrooms, in the mission field, in our homes or one by one — He promises to help us do His work; we were never meant to do it alone. Before the Savior taught His disciples where to go and what to teach, He taught them who to become: His first lesson was about discipleship, and at the heart of discipleship is love. For the Master Teacher, every lesson was inspired by love for those He taught. Christ-centered teaching is rooted in relationships, and the inspired new Sunday schedule offers weekly opportunities to know and love those we teach, helping them come closer to the Savior and deepen their conversion — His pattern for every gospel lesson, even shorter ones. He invited all to come unto the Master Teacher, learn of Him and love Him, and He will help us love those we teach.",
   [],
   ["To teach like the Savior, we must love like the Savior.",
    "The impact of a gospel teacher is not just the message — it is the love of the messenger.",
    "Learn of Him. Love Him. And as you do, He will help you love those you teach — and that love will make your teaching more like His."],
   "Come unto the Master Teacher — learn of Him and love Him, and let that love shape how you teach those around you.",
   "Whom do I teach — at church, at home or one by one — and how could I come to know and love them better?"),
 t("sun-pm-9-gilbert", "sun-pm", 9, "Elder Clark G. Gilbert", "Quorum of the Twelve Apostles", "Teach Truth With Love",
   "https://www.thechurchnews.com/general-conference/2026/10/04/elder-clark-gilbert-october-2026-general-conference-teach-truth-with-love/",
   "Speaking about standing for truth with love. Standing for truth takes courage, and standing for truth with love takes even more. Drawing on teachings of President Dallin H. Oaks, he shared five principles: avoid overly contentious settings, where tense moments make it harder to see what is really causing someone’s protests; find common ground, as the Savior did, for “we love him, because he first loved us”; be a light, which opens more doors than any pointed argument; hold to truth even in outreach, because minimizing God’s laws separates us from the One who loves others most; and stay anchored in Jesus Christ, asking ourselves whether we carry Christlike attributes as we strive to stand for truth with love. For disciples of Jesus Christ, truth and love always walk together — for some this will require greater conviction, for others greater charity, and the Lord will help us.",
   ["1 John 4:19"],
   ["It takes courage to stand for truth. It takes even more courage to stand for truth with love.",
    "The best way to help someone else keep their covenants is to keep your covenants.",
    "For disciples of Jesus Christ, truth and love always walk together. I believe teaching truth with love will be the hallmark of Christ’s disciples in the last days."],
   "Stand for truth with love — avoid contention, find common ground, be a light, hold to truth, and stay anchored in Jesus Christ.",
   "Do I need greater conviction or greater charity to teach truth with love — and where can I start this week?"),
]

# 60-second recap "big idea" — a one-line condensation of the doc's summary (NOT a quote).
BIG_IDEAS = {
 "sat-am-1-gong": "The temple is the Lord's place of spiritual safety and holiness — every temple testifies of Christ.",
 "sat-am-2-runia": "God sculpts our souls through the very things that make life hard; invite Him to do His work.",
 "sat-am-3-causse": "Every disciple can bear witness of Christ — a testimony need only be true.",
 "sat-am-4-sikahema": "Don't take living prophets for granted; earlier Saints sacrificed greatly to hear them.",
 "sat-am-5-hathaway": "Jesus Christ delivers in His time and way; He has not forgotten you.",
 "sat-am-6-soares": "Fasting with intentional prayer is worship that draws heaven near.",
 "sat-am-7-douglas": "Missionary service is the most important work; there's a place reserved for you.",
 "sat-am-8-christofferson": "Gambling is morally wrong; live on a higher plane and use time and means for good.",
 "sat-pm-1-renlund": "Remember what God has already done so you can trust His promises now.",
 "sat-pm-2-farnes": "God places people in our path — minister to the person in front of you.",
 "sat-pm-3-chigbundu": "Scriptures, prayer, sacrament and covenants build spiritual immunity — the armor of God.",
 "sat-pm-4-giuffra": "Tithing is a law of faith; don't withhold its blessings from anyone.",
 "sat-pm-5-morgan": "Covenants reach across generations; your family's story isn't finished.",
 "sat-pm-6-fale": "Knowing you are a child of God protects from deception and gives life purpose.",
 "sat-pm-7-kearon": "Seek spiritual lift, turn from sink, and show others where to rise — Jesus lives to lift.",
 "sat-pm-8-dunn": "Give your 90%; the Savior helps with the final 10% by lengthening our stride.",
 "sat-pm-9-eyring": "In turbulent times, the Holy Ghost is the true source of comfort and hope.",
 "sat-pm-10-rasband": "Give your despair for wayward loved ones to Christ, and keep loving like Jesus.",
 "sun-am-1-eyring": "The Lord keeps His promise ‘Fear not, I am with thee’ — and trusts us to help comfort others.",
 "sun-am-2-chibota": "See others as children of God — pray to see as He sees, and lift labels with His grace.",
 "sun-am-3-andersen": "Faith in Christ gives spiritual courage to choose the right — and courage in turn strengthens that faith.",
 "sun-am-4-fantone": "Take His name by covenant — lose yourself in serving others, and find Him (and yourself).",
 "sun-am-5-dube": "Come unto Christ as you are — He perfects us; we do not perfect ourselves first.",
 "sun-am-6-cook": "Integrity, virtue and daily repentance lead to happiness and the Holy Ghost’s companionship.",
 "sun-am-7-kyungu": "Forgo harsh words; use the language of peacemakers that uplifts and preserves relationships.",
 "sun-am-8-schmeil": "Consider your ways — build your relationship with God through covenants, and He will bless you.",
 "sun-am-9-oaks": "The gospel of Jesus Christ is for all — overcome by getting closer to the Savior, and help others come unto Him.",
 "sun-pm-1-uchtdorf": "Jesus Christ unites His covenant people — the closer we come to Him, the closer we come to each other.",
 "sun-pm-2-spannaus": "Heavenly Father knows you and is at your side — put Him first, and He will guide your righteous desires.",
 "sun-pm-3-villanueva": "Live the law of tithing and the Lord opens the windows of heaven — blessings both temporal and spiritual.",
 "sun-pm-4-bednar": "Ordinances and covenants are spiritual credentials — kept faithfully, they are sealed by the Holy Spirit of Promise.",
 "sun-pm-5-lebethoa": "Whatever we face, the answer is always Jesus Christ — faith, daily scripture study and daily repentance let in His light.",
 "sun-pm-6-sinclair": "Be quick to help and slow to judge — like Christ at the well, look to a person's possible, not only their past.",
 "sun-pm-7-stevenson": "Gospel truths are like a favorite fruit — they grow sweet as we live them; love, share and invite others to taste them.",
 "sun-pm-8-reid": "You are good enough to teach — the Lord will help you, and teaching like the Savior begins with loving like the Savior.",
 "sun-pm-9-gilbert": "Stand for truth with love — for disciples of Jesus Christ, truth and love always walk together.",
}
for _t in talks:
    _t["big_idea"] = BIG_IDEAS[_t["id"]]
    # Official video: paste ONLY an embed URL the Church makes embeddable (e.g. the official
    # General Conference YouTube video's embed link) once posted. None = show link instead.
    _t["video_embed"] = None
    # Full talk text is Church copyright. Keep False unless written permission is granted.
    _t["full_text_permitted"] = False

# Public site URL used for QR codes, deep links and Open Graph tags. SET BEFORE PUBLISHING.
# ---- SINGLE DOMAIN CONFIG ----
# Planned custom domain (bought Oct 2026; live). Flip DOMAIN_LIVE to True once it's bought and pointed at
# GitHub Pages; cards, QR codes and canonical/OG URLs then switch to the domain automatically.
DOMAIN = "sixmonthsoflight.com"
DOMAIN_LIVE = True
SITE_URL = f"https://{DOMAIN}/" if DOMAIN_LIVE else "https://briganator.github.io/six-months-of-light/"

site = {
  "site_name": "Six Months of Light",
  "tagline": "The words of October 2026 General Conference, to carry you to April.",
  "title": "October 2026 General Conference",
  "site_url": SITE_URL,
  "domain": DOMAIN,
  "domain_live": DOMAIN_LIVE,
  "subtitle": "196th Semiannual General Conference · October 3–4, 2026",
  "updated": "Sunday, October 4, 2026",
  "conference_url": "https://www.churchofjesuschrist.org/study/general-conference/2026/10?lang=eng",
  "talk_of_the_week": {"talk_id": "sat-pm-7-kearon",
     "ponder": "What are the subtle signs of “sink” in my week?",
     "invitation": "This week, notice what lifts and what sinks — turn decisively toward the Spirit, and show one person where the lift is."},
  "sessions": sessions, "talks": talks,
  "challenge": {"id": "challenge-oct-2026", "title": "The Lift Challenge",
     "text": "For 7 days, choose one invitation from a Saturday talk and act on it. Then share a short story of what happened.",
     "note": "Stories are reviewed before they appear."},
}
out = pathlib.Path(__file__).resolve().parent.parent / "assets" / "data.js"
out.write_text("// GENERATED by tools/talks_source.py — edit that file, then run: python3 tools/talks_source.py\nwindow.CONF = " + json.dumps(site, ensure_ascii=False, indent=1) + ";\n")
print("wrote", out, len(talks), "talks")
