# Source of truth for the site content. Transcribed from the Google Doc
# "October 2026 General Conference — Study Guide" (Saturday sessions, from recaps).
# Personal application sections and private notes are intentionally EXCLUDED.
# Quotes are copied verbatim from the doc (as reported in recaps). Do not add quotes
# that are not in the doc. Replace with official text once posted.
import json, pathlib

SAT_AM = "https://www.churchofjesuschrist.org/study/general-conference/2026/10/saturday-morning-session?lang=eng"
SAT_PM = "https://www.churchofjesuschrist.org/study/general-conference/2026/10/saturday-afternoon-session?lang=eng"
SUN_AM = "https://www.churchofjesuschrist.org/study/general-conference/2026/10/sunday-morning-session?lang=eng"
SUN_PM = "https://www.churchofjesuschrist.org/study/general-conference/2026/10/sunday-afternoon-session?lang=eng"
CN = "https://www.thechurchnews.com/general-conference/2026/10/03/"

sessions = [
  {"id": "sat-am", "color": "dawn", "name": "Saturday Morning Session", "when": "Sat, Oct 3 · 10:00am–noon MDT", "url": SAT_AM, "status": "complete",
   "note": "Conducted by President Henry B. Eyring. Music by The Tabernacle Choir at Temple Square."},
  {"id": "sat-pm", "color": "amber", "name": "Saturday Afternoon Session", "when": "Sat, Oct 3 · 2:00–4:00pm MDT", "url": SAT_PM, "status": "complete",
   "note": "Conducted by Elder Neil L. Andersen. Music by a choir from Northern Utah."},
  {"id": "sun-am", "color": "sky", "name": "Sunday Morning Session", "when": "Sun, Oct 4 · 10:00am–noon MDT", "url": SUN_AM, "status": "pending",
   "note": "Conducted by President D. Todd Christofferson. Music by The Tabernacle Choir at Temple Square (opening hymn: How Firm a Foundation). Talks are being added as Church News recaps post."},
  {"id": "sun-pm", "color": "violet", "name": "Sunday Afternoon Session", "when": "Sun, Oct 4 · 2:00–4:00pm MDT", "url": SUN_PM, "status": "pending",
   "note": "Talks will be added after the session."},
]

def t(id, session, order, speaker, calling, title, recap, summary, scriptures, quotes, invitation, ponder, official_url=None):
    recap_url = recap if recap.startswith("http") else CN + recap
    return dict(id=id, session=session, order=order, speaker=speaker, calling=calling, title=title,
                recap_url=recap_url, official_url=official_url, summary=summary, scriptures=scriptures,
                quotes=quotes, invitation=invitation, ponder=ponder)

talks = [
 t("sat-am-1-gong", "sat-am", 1, "Elder Gerrit W. Gong", "Quorum of the Twelve Apostles", "Come to the Lord in His Holy House",
   "elder-gerrit-w-gong-october-2026-general-conference-come-to-the-lord-holy-house-temple/",
   "In a world of commotion and contention, the Lord invites us to a place of spiritual safety, harmony and holiness — His holy house. Agency, faith, repentance and Christ's Atonement make change and forgiveness possible, and temple service softens hearts on both sides of the veil. Everything in every temple testifies of Christ. Look for the miracles and build a personal temple culture.",
   ["Temple inscription “Holiness to the Lord, the House of the Lord” (no verse reported in recaps)"],
   ["While we are grateful our temples and everything in them are physically beautiful, let us celebrate and treasure even more the spiritual blessings temples bring.",
    "Covenants are not big or small. Please let us never speak of a temple as big or small, elaborate or plain.",
    "Dear brothers and sisters, come worship and rejoice with the Lord in the house of the Lord, in temple doctrine and in your personal temple culture."],
   "Come worship and rejoice in the house of the Lord; look for the miracles.",
   "What does my “personal temple culture” look like right now — and our family's?"),
 t("sat-am-2-runia", "sat-am", 2, "Sister Tamara W. Runia", "First Counselor, Young Women General Presidency", "The Sculpting of Our Souls",
   "sister-tamara-runia-october-2026-general-conference-sculpting-souls/",
   "Tempering, refining experiences are part of necessary mortal growth — “all these things shall give thee experience.” The gospel isn't an umbrella that keeps the rain off; it's the solid rock we stand on during the storm. A godlike life is carved from the very things that make it hard, and God waits for our invitation before He really goes to work. She shared the sudden death of her son, a young father.",
   ["Doctrine and Covenants 122:7", "Helaman 5:12"],
   ["God's love has moved me from questions that begin with ‘why’ to reflections that begin, ‘I know that God loves me, so what is supposed to be happening here?’",
    "Christ's work in your life and His love for you are bigger than your present story. And He can fix what feels badly broken.",
    "God is shaping us into something only He knows we can become."],
   "Invite God to do His sculpting work. He can fix what feels badly broken.",
   "Where am I still asking “why” instead of “what is supposed to be happening here?”"),
 t("sat-am-3-causse", "sat-am", 3, "Elder Gérald Caussé", "Quorum of the Twelve Apostles", "The Gift of Testimony",
   "elder-gerald-causse-october-2026-general-conference-gift-of-testimony/",
   "Apostles are special witnesses of Christ, but the privilege of bearing witness extends to all disciples and is a way to keep our baptismal covenant. Testimony is deeply personal and grows through faith, seeking, living the gospel and the Holy Ghost. A sincere, humble testimony has power to change both giver and receiver. Look for daily opportunities — at home, at church, ministering, online and in everyday conversations.",
   ["Doctrine and Covenants 107:23", "Mosiah 18:9"],
   ["Bearing witness is a foundational responsibility of discipleship.",
    "Your testimony may be different from mine or that of other family members or fellow Saints. Please trust it, nurture it and bear it, because it is uniquely yours.",
    "There is great power in a sincere, humble and heartfelt testimony. It need not be long, eloquent or dramatic — it only needs to be true."],
   "Look for opportunities each day to bear witness of Jesus Christ, even briefly.",
   "When did I last simply and briefly testify of Christ at home?"),
 t("sat-am-4-sikahema", "sat-am", 4, "Elder Vaiangina Sikahema", "General Authority Seventy", "Prophets, Seers and Revelators",
   "elder-sikahema-october-2026-general-conference-prophets-seers-revelators/",
   "In 1947 his grandparents sailed across the Tongan islands to hear a visiting apostle; their infant son died on the journey, yet they buried him and continued. People through the ages have yearned for prophetic voices. Today we can see and hear prophets on our phones, yet many take them for granted. What a blessing to live when apostles and prophets are on the earth.",
   ["Doctrine and Covenants 90:5"],
   ["What a blessing it is to live in a time when apostles and prophets are on the earth.",
    "I suspect the Lord knew that even when we would have these devices [cellphones] to easily see and hear His anointed servants, many of us would still take them for granted.",
    "Let us not be guilty of holding the oracles of God ‘as a light thing.’"],
   "Don't hold the oracles of God as a light thing; give prophetic words the effort earlier Saints sacrificed for.",
   "Do I treat conference as background noise or as an appointment?"),
 t("sat-am-5-hathaway", "sat-am", 5, "Elder Kevin J. Hathaway", "General Authority Seventy", "Jesus Christ Is the Great Deliverer",
   "elder-kevin-j-hathaway-october-2026-general-conference-jesus-christ-deliverer/",
   "Scripture shows a pattern of divine deliverance: opposition that raises heart-rending questions; sincere seeking through prayer, fasting and scripture study; assurance that the Savior visits us in our afflictions as we keep covenants; enabling grace that strengthens us without removing all pain; and deliverance in His time and way. When it feels too late, remember Jairus.",
   ["Mark 5:36", "Luke 8:50 (“Be not afraid, only believe”)"],
   ["With perfect understanding and infinite power, He can deliver the righteous from all things, forever.",
    "The Lord is not delayed, distracted or derelict in His deliverance. He has not forgotten you.",
    "Some miracles are immediate, some come after long waiting, and some await the Resurrection."],
   "Trust that in His time and way, Jesus Christ will deliver you.",
   "What am I waiting on the Lord for right now, and what growth might the waiting be producing?"),
 t("sat-am-6-soares", "sat-am", 6, "Elder Ulisses Soares", "Quorum of the Twelve Apostles", "A Higher and Holier Fast",
   "elder-ulisses-soares-october-2026-general-conference-higher-and-holier-fast/",
   "The Lord's call to fast echoes Isaiah, with promised blessings of light after darkness, healing, and assurance that He is near. A sincere fast is accompanied by earnest, intentional prayer, and finds its highest expression in Jesus Christ. Fasting is an act of worship that refines discipleship and prepares us for revelation; fast offerings help “let the oppressed go free.”",
   ["Isaiah 58:6"],
   ["A sincere and faithful fast is accompanied by earnest and intentional prayer.",
    "[Fasting and prayer] may not remove every burden from our path, but they draw heaven near and endow us with divine power to overcome or endure whatever circumstances we may face.",
    "I invite you to prayerfully ponder Isaiah's teachings and more intentionally embrace the divine purpose of the law of the fast in a higher and holier way as part of our worship."],
   "Ponder Isaiah's teachings and embrace the law of the fast more intentionally as worship.",
   "Is my fast a skipped meal or an act of worship with a clear purpose?"),
 t("sat-am-7-douglas", "sat-am", 7, "Bishop Sean Douglas", "Second Counselor, Presiding Bishopric", "The Hour of Your Mission Is Come",
   "bishop-sean-douglas-october-2026-general-conference-hour-your-mission-come/",
   "Missionaries are divinely commissioned to invite God's children to come unto Christ; they are both messengers and living examples. Elder Merlin Sanchez's story showed how a mission builds lifelong discipleship. Worthy, able young men have a priesthood responsibility to serve; young women are invited to prayerfully consider serving. Missionaries of all ages find joy in the work.",
   ["No specific verses reported in recaps"],
   ["Make no mistake — you are doing the most important work you could be doing.",
    "To all the rising generation of the Church, I invite you to place serving a full-time mission high on your list.",
    "There is still plenty of room and a special place reserved for each of you. We need you. ‘Come join the ranks.’"],
   "Rising generation: place a full-time mission high on your list. Senior missionaries are welcome too.",
   "What did the Spirit highlight for me in this talk? What one invitation will I act on this week?"),
 t("sat-am-8-christofferson", "sat-am", 8, "President D. Todd Christofferson", "Second Counselor in the First Presidency", "O Be Wise",
   "president-d-todd-christofferson-october-2026-general-conference-gambling/",
   "Gambling has exploded, made continuous and private by smartphones, and disproportionately affects youth and young adults. Beyond lost money, it displaces saving, increases debt and brings family and social costs. Gambling is morally wrong — built on desiring something for nothing — and crowds out things of value. He pled for us to live on a higher plane and use saved time and resources for good.",
   ["Jacob 6:12 (“O be wise; what can I say more?”)", "Doctrine and Covenants 58:27"],
   ["For us as Latter-day Saints, overarching all other concerns is the fact that gambling is morally wrong. Gambling is built on the desire to obtain something for nothing.",
    "Today, I am pleading with all of us to live life on a higher plane.",
    "Work leads to prosperous, just and equitable societies. Gambling, even for fun, leads in the opposite direction."],
   "Refrain from gambling and use the time and resources saved for doing good.",
   "What “good cause” could absorb time I currently spend on idle pursuits?"),
 t("sat-pm-1-renlund", "sat-pm", 1, "Elder Dale G. Renlund", "Quorum of the Twelve Apostles", "How Long Will It Be Ere They Believe Me",
   "elder-dale-g-renlund-october-2026-general-conference-trust-savior/",
   "A heart-transplant patient who survived against overwhelming odds later complained about cold oatmeal. Like him, and like ancient Israel, we can fixate on the here and now and lose sight of the bigger picture and God's promises. God invites us to trust Him; Christ has overcome the world, and His power to save is infinite and intimate.",
   ["Numbers 14:11", "cf. John 16:33"],
   ["God invites us to trust Him and His promises.",
    "Jesus overcame the world; we do not have to do so ourselves. When our faith is centered on Jesus Christ, He promises spiritual peace no matter our circumstances.",
    "As we reflect on the great things the Lord has already done and remember His goodness and mercy, we are better positioned to grasp the bigger picture and to rely on His promises to us. We can trust Him."],
   "Remember what the Lord has already done and rely on His promises personally.",
   "What is my “cold oatmeal” — the small frustration crowding out a miracle?"),
 t("sat-pm-2-farnes", "sat-pm", 2, "President Timothy L. Farnes", "Young Men General President", "Divine Appointments",
   "president-farnes-october-2026-general-conference-divine-appointments/",
   "As covenant followers of Jesus Christ we minister with compassion to whomever God places in our path, because that's what the Savior did. Taking His name means seeing as He sees, feeling as He feels and doing as He would do, so people experience something of Christ in us. God places people in our path — “divine appointments.”",
   ["Sacrament covenant to take Christ's name (no specific verse reported in recaps)"],
   ["As covenant followers of Jesus Christ, we minister with compassion to whomever God places in our path.",
    "When someone encounters us, they should experience something of Jesus Christ — His kindness, His patience, His hope, His love, His compassion.",
    "Let us pray every day for eyes to see the divine appointments God places before us. Let us put compassion into action and minister to the person in front of us. It's what Jesus did."],
   "Pray daily for eyes to see divine appointments and minister to the person in front of you.",
   "Who did God place in my path this week that I walked past?"),
 t("sat-pm-3-chigbundu", "sat-pm", 3, "Elder Christian C. Chigbundu", "General Authority Seventy", "Spiritual Immunity",
   "elder-christian-chigbundu-october-2026-general-conference-spiritual-immunity/",
   "These are troubled times, but we need not fear. Build spiritual immunity through four small and simple things: daily meaningful scripture study; prayer; the sacrament, remembered throughout the week; and covenants, including temple worship. Together they are the armor of God.",
   ["Alludes to the “armor of God” and “small and simple” things (no verse cited in recaps)"],
   ["As we build our spiritual immunity, we develop the strength and courage to withstand the challenges of life.",
    "Remember that trials may come, yet, as we worship in the temple and remember our covenants, we receive personal direction from the Lord that will guide us along the covenant path.",
    "I invite you to always remember scriptures, prayers, sacrament and covenants. While they may seem small and simple, they are truly the armor of God."],
   "Always remember scriptures, prayers, sacrament and covenants.",
   "Which of the four (scriptures, prayer, sacrament, covenants) is weakest in my week?"),
 t("sat-pm-4-giuffra", "sat-pm", 4, "Elder Patricio M. Giuffra", "General Authority Seventy", "Trusting the Lord Through Tithes and Offerings",
   "elder-patricio-giuffra-october-2026-general-conference-tithing-offerings/",
   "As a missionary in Chile he taught a 70-year-old woman who cleaned houses to pay rent and said she couldn't pay tithing. His mission president said he was “no one to deny this sister the blessings of the law of tithing.” She prayed for help, was baptized and paid tithing faithfully. The Lord keeps His promises; the windows of heaven open according to obedience.",
   ["Alludes to the “windows of heaven” promise (Malachi 3:10)"],
   ["Commandments are given to draw us closer to the Savior, to protect us and to help us remain free from sin and many of the challenges the world presents.",
    "Even when we do not understand the purpose of our trials, we can have the assurance that the Lord knows our circumstances, honors our obedience and fulfills His promises in His own time and way.",
    "I testify that the law of tithing is a law of faith. As we obey it, we demonstrate our trust in the Lord and allow Him to work miracles in our lives, often in ways we do not expect."],
   "Trust the Lord's promises; don't withhold the blessings of a commandment from others by lowering the standard.",
   "Where am I tempted to “make an exception” for someone and withhold the blessing of a commandment?"),
 t("sat-pm-5-morgan", "sat-pm", 5, "Elder Jeremiah J. Morgan", "General Authority Seventy", "The Infinite Power of God in Our Covenants",
   "elder-jeremiah-morgan-october-2026-general-conference-infinite-power-of-god-in-covenants/",
   "His mother read the Book of Mormon aloud to him every day, whether he listened or not; as a young man he came to know this is the Lord's Church and was baptized at 18. Covenants that came before him reached after him. Covenant faithfulness doesn't override a child's agency, but it has a generational impact. Don't lose hope in loved ones who have wandered.",
   ["Echoes Hebrews 12:2 (“author and finisher”)"],
   ["No time or effort is ever wasted in reading the Book of Mormon. Not for you, not for your children, not for your family, not for anyone.",
    "Covenants with God are filled with incalculable power.",
    "Don't ever give up. Your story, your family's story, is not all written. God is the author and the finisher of it."],
   "Keep reading the Book of Mormon with your family; never give up.",
   "Whose covenants have reached after me?"),
 t("sat-pm-6-fale", "sat-pm", 6, "Elder Hutch U. Fale", "General Authority Seventy", "I Am a Child of God",
   "elder-hutch-fale-october-2026-general-conference-i-am-a-child-of-god/",
   "“I am a child of God, and He loves me” is true for everyone. Understanding the Father's love and our identity prevents deception, gives purpose to mortality and brings power, peace and comfort. Beware the lie that we can be saved regardless of sin. Knowing His love helps us reject divisive labels and know it's not too late to turn to Christ. Families, despite imperfections, often teach us God's love.",
   ["Luke 15 (prodigal son, lost sheep)"],
   ["Understanding our Father's love and our true identity as His children is essential for our daily and eternal happiness. It prevents deception and gives purpose to this mortal life.",
    "From the prodigal son to leaving the 99 sheep to find the one, our Father's message, through His Son, has always been that there is still yet time, if we turn to Christ today.",
    "It is often through families, despite all their imperfections, that Our Father teaches us about His love."],
   "Turn to Christ today — there is still time.",
   "Which labels do I accept above “child of God”?"),
 t("sat-pm-7-kearon", "sat-pm", 7, "Elder Patrick Kearon", "Quorum of the Twelve Apostles", "Jesus Lives to Lift",
   "elder-patrick-kearon-october-2026-general-conference-jesus-lives-lift/",
   "Drawing on flying gliders as a teenager, he taught spiritual “lift” and “sink.” Lift can't be seen but can be felt through the Holy Spirit, drawing us toward Christ. Seek the feelings of the Holy Ghost and join those who are climbing; watch for subtle signs of sink and turn away decisively; and when you find lift, show others where and how to rise.",
   ["The Savior “lifted up” on the cross; His followers “shall be lifted up at the last day” (no verse cited in recaps)"],
   ["At the heart of our faith is the glorious truth that we have an adoring Father in Heaven, whose Son, our Savior, loves to lift.",
    "We can learn to live in spiritual lift. And when we sink, our gentle Savior is there to lift us up as we turn to Him.",
    "Your Savior is your lift. He is your ever-rising air. There is no limit to how high you can climb with Him. Jesus Christ lives to lift."],
   "Seek lift, turn decisively away from sink, and show others where to rise.",
   "What are the subtle signs of “sink” in my week?"),
 t("sat-pm-8-dunn", "sat-pm", 8, "Elder Michael A. Dunn", "General Authority Seventy", "The 90 and 10",
   "elder-dunn-october-2026-general-conference-90-and-9/",
   "Comparing mortality to an ultramarathon he was ready to quit long before the finish, he taught that races can devolve from running to walking to shuffling. The Savior bears our griefs and magnifies our smallest offerings. Giving 90% of a spiritual journey may take all we have; the Savior extends His hand for the final 10%.",
   ["Hymn “Lord, I Would Follow Thee” (Hymns, no. 220)"],
   ["The Redeemer rescues not by shortening our course, but by helping us lengthen our stride.",
    "Don't confuse the perceived invisibility of the Lord's hand with the inveterate nature of the Lord's heart.",
    "Peace will come even when hoped-for outcomes do not."],
   "Give what you can; trust the Savior for the final 10%.",
   "Where am I shuffling right now, and what would “lengthening my stride” look like?"),
 t("sat-pm-9-eyring", "sat-pm", 9, "Elder Matthew J. Eyring", "General Authority Seventy", "Comfort From the Holy Ghost",
   "elder-matthew-j-eyring-october-2026-general-conference-comfort-holy-ghost/",
   "Every child of God faces challenges impossible to overcome without the Savior. Handing burdens to the Lord lets us see His promise fulfilled: draw near to Him and He will draw near. In increasing turbulence, true comfort will become scarcer. The Savior's peace is made manifest through the comforting power of the Holy Ghost.",
   ["Doctrine and Covenants 88:63"],
   ["In a world of increasing temporal and spiritual turbulence, true sources of comfort will become more scarce. … There is hope in Jesus Christ.",
    "Someday we will more fully realize how generous and kind the Lord has been to each of us.",
    "Living worthy of the constant companionship of the Holy Ghost should be one of our highest priorities."],
   "Make living worthy of the Holy Ghost's constant companionship a top priority.",
   "Where do I turn first for comfort — the Holy Ghost or something else?"),
 t("sat-pm-10-rasband", "sat-pm", 10, "Elder Ronald A. Rasband", "Quorum of the Twelve Apostles", "Love Like Jesus",
   "elder-ronald-a-rasband-october-2026-general-conference-love-like-jesus-wayward-souls/",
   "Many hearts ache for loved ones who have turned away. By divine design, each person must choose for themselves to follow Christ. Turn your despair over to Jesus Christ — we cannot change their hearts, but He can. Love is the centerpiece of His gospel. Let go of guilt; Christ has already paid for the choices of those we grieve for. Keep loving, praying, and never give up.",
   ["No specific verses reported in recaps"],
   ["I ask you to turn over to Jesus Christ your despair for those wayward souls. We cannot change their hearts, but He can; He is a God of miracles.",
    "Love is not stepping back or sanctioning others' decisions and actions. Love is being interested in their lives, their successes and their challenges. Love is being there with arms outstretched and a cheerful countenance.",
    "He knows them. He knows their hearts; He loves them. He gave His very life to bring them home, all the way home."],
   "Turn your despair over to Christ; let go of guilt; keep loving and praying.",
   "Whom am I carrying guilt or despair for that I need to give to Christ?"),
 t("sun-am-1-eyring", "sun-am", 1, "President Henry B. Eyring", "First Counselor in the First Presidency", "Fear Not, I Am With Thee",
   "https://www.thechurchnews.com/general-conference/2026/10/04/president-henry-b-eyring-october-2026-general-conference-fear-not-i-am-with-thee/",
   "President Eyring spoke about helping give the Lord's comfort to others. The Lord's promised comfort in Isaiah 41 and the hymn “How Firm a Foundation” (“Hymns,” No. 85) will become more important and more precious. Mortal tests are hard because we must grow in spiritual cleanliness and stature to live in God's presence; Heavenly Father gave us a Savior and the power to choose by faith to keep commandments, repent and come unto Him. The promise is not for the removal of challenges. The Lord sends faithful disciples to help Him keep His promise to succor others; we are invited to join Him in that work.",
   ["Isaiah 41:10", "Hymn “How Firm a Foundation” (Hymns, no. 85)"],
   ["It is because He knows that we must grow in spiritual cleanliness and stature to be able to live in His presence. To make that possible, Heavenly Father gave us a Savior and the power to choose for ourselves by faith to keep His commandments and to repent and to come unto Him.",
    "The Lord sends faithful disciples to help Him keep his promise to succor others in their distress.",
    "We shed tears of joy and take courage whenever we hear the words, ‘Fear not, I am with thee,’ and we are touched that He offers us the trust of helping and loving others."],
   "Join the Lord in keeping His promise — help Him comfort and succor those in distress.",
   "Whom is the Lord inviting me to comfort for Him today?"),
 t("sun-am-2-chibota", "sun-am", 2, "President Rosemary K. Chibota", "Primary General President", "A Child of God",
   "https://www.thechurchnews.com/general-conference/2026/10/04/president-rosemary-chibota-october-2026-general-conference-a-child-of-god/",
   "Primary General President Rosemary K. Chibota spoke about seeing each other as children of God. The Southern African greeting “Sawubona” means “I see you” — an acknowledgment of another person’s worth and humanity. Jesus Christ saw people as beloved sons and daughters of God rather than by labels. The world invites focus on labels, but labels never fully capture who we truly are; eternal identity matters more. Whatever labels weigh heavily, Jesus Christ’s grace is sufficient to lift above every label and limitation. She invited disciples this week to learn the name of someone who may feel unseen, pray to see others as Heavenly Father sees them, and replace worldly labels with the eternal truths: child of God, child of the covenant, disciple of Jesus Christ.",
   ["No specific verses reported in recaps"],
   ["The world invites us to focus on labels rather than eternal identity. However, labels can never fully capture who we truly are",
    "When we ask Heavenly Father to help us see others, He guides us to those who feel unseen.",
    "When we see one another through the Savior’s eyes, hearts change, relationships deepen and faith grows."],
   "Pray to see others as Heavenly Father sees them; learn the name of someone who may feel unseen.",
   "Whom am I labeling instead of seeing as a child of God?"),
 t("sun-am-3-andersen", "sun-am", 3, "Elder Neil L. Andersen", "Quorum of the Twelve Apostles", "Courage Born of Our Faith in Jesus Christ",
   "https://www.thechurchnews.com/general-conference/2026/10/04/elder-andersen-october-2026-general-conference-courage-born-of-faith/",
   "Elder Neil L. Andersen of the Quorum of the Twelve Apostles spoke about spiritual courage being born of faith in Jesus Christ. Faith and courage are hallmarks of Jesus Christ’s disciples. As we choose faith in Christ, He blesses us with courage to choose the right even in difficult situations, and as we manifest that courage, our faith strengthens. Discipleship always requires spiritual courage; courage is born of faith in Jesus Christ. Being His true disciple — overcoming the world, keeping commandments, trusting Him and His promises — is not a casual pursuit. Spiritual courage is the triumph over obstacles, doubt, and fear in choosing the right. With the world in constant commotion, disciples need stillness to nourish their faith in Christ. Even when troubled on every side, they are not in despair when hope is alive in Christ (2 Corinthians 4:8). Faith in Him brings spiritual courage to minister, keep commandments, speak openly of the Savior, be guided by the Holy Ghost, repent, and receive forgiveness.",
   ["2 Corinthians 4:8"],
   ["As we choose faith in Christ, He blesses us with the courage, sometimes in very difficult situations, to choose the right, and as we manifest our courage to choose the right, our faith in Christ strengthens.",
    "It is our faith in Christ that gives us the spiritual courage to speak openly to others of our Savior, make covenants in the house of the Lord, repent and receive forgiveness, follow living prophets and be guided by the quiet impressions of the Holy Ghost.",
    "I promise you that as you strengthen your faith in Jesus Christ by believing and following Him and keeping His commandments, your answers will come, your spiritual power will increase, and your courage in following Christ will define your eternal soul."],
   "Strengthen your faith in Jesus Christ by believing, following Him, and keeping His commandments.",
   "Where do I need spiritual courage right now — and how will I strengthen my faith in Christ to receive it?"),
]

# 60-second recap "big idea" — a one-line condensation of the doc's summary (NOT a quote).
BIG_IDEAS = {
 "sat-am-1-gong": "The temple is the Lord's place of spiritual safety and holiness — every temple testifies of Christ.",
 "sat-am-2-runia": "God sculpts our souls through the very things that make life hard; invite Him to do His work.",
 "sat-am-3-causse": "Every disciple can bear witness of Christ — a testimony need only be true.",
 "sat-am-4-sikahema": "Don't take living prophets for granted; earlier Saints sacrificed greatly to hear them.",
 "sat-am-5-hathaway": "Jesus Christ delivers in His time and way; He has not forgotten you.",
 "sat-am-6-soares": "Fasting with intentional prayer is worship that draws heaven near.",
 "sat-am-7-douglas": "Missionary service is the most important work; there's a place reserved for you.",
 "sat-am-8-christofferson": "Gambling is morally wrong; live on a higher plane and use time and means for good.",
 "sat-pm-1-renlund": "Remember what God has already done so you can trust His promises now.",
 "sat-pm-2-farnes": "God places people in our path — minister to the person in front of you.",
 "sat-pm-3-chigbundu": "Scriptures, prayer, sacrament and covenants build spiritual immunity — the armor of God.",
 "sat-pm-4-giuffra": "Tithing is a law of faith; don't withhold its blessings from anyone.",
 "sat-pm-5-morgan": "Covenants reach across generations; your family's story isn't finished.",
 "sat-pm-6-fale": "Knowing you are a child of God protects from deception and gives life purpose.",
 "sat-pm-7-kearon": "Seek spiritual lift, turn from sink, and show others where to rise — Jesus lives to lift.",
 "sat-pm-8-dunn": "Give your 90%; the Savior helps with the final 10% by lengthening our stride.",
 "sat-pm-9-eyring": "In turbulent times, the Holy Ghost is the true source of comfort and hope.",
 "sat-pm-10-rasband": "Give your despair for wayward loved ones to Christ, and keep loving like Jesus.",
 "sun-am-1-eyring": "The Lord keeps His promise ‘Fear not, I am with thee’ — and trusts us to help comfort others.",
 "sun-am-2-chibota": "See others as children of God — pray to see as He sees, and lift labels with His grace.",
 "sun-am-3-andersen": "Faith in Christ gives spiritual courage to choose the right — and courage in turn strengthens that faith.",
}
for _t in talks:
    _t["big_idea"] = BIG_IDEAS[_t["id"]]
    # Official video: paste ONLY an embed URL the Church makes embeddable (e.g. the official
    # General Conference YouTube video's embed link) once posted. None = show link instead.
    _t["video_embed"] = None
    # Full talk text is Church copyright. Keep False unless written permission is granted.
    _t["full_text_permitted"] = False

# Public site URL used for QR codes, deep links and Open Graph tags. SET BEFORE PUBLISHING.
# ---- SINGLE DOMAIN CONFIG ----
# Planned custom domain (bought Oct 2026; live). Flip DOMAIN_LIVE to True once it's bought and pointed at
# GitHub Pages; cards, QR codes and canonical/OG URLs then switch to the domain automatically.
DOMAIN = "sixmonthsoflight.com"
DOMAIN_LIVE = True
SITE_URL = f"https://{DOMAIN}/" if DOMAIN_LIVE else "https://briganator.github.io/six-months-of-light/"

site = {
  "site_name": "Six Months of Light",
  "tagline": "The words of October 2026 General Conference, to carry you to April.",
  "title": "October 2026 General Conference",
  "site_url": SITE_URL,
  "domain": DOMAIN,
  "domain_live": DOMAIN_LIVE,
  "subtitle": "196th Semiannual General Conference · October 3–4, 2026",
  "updated": "Sunday, October 4, 2026",
  "conference_url": "https://www.churchofjesuschrist.org/study/general-conference/2026/10?lang=eng",
  "talk_of_the_week": {"talk_id": "sat-pm-7-kearon",
     "ponder": "What are the subtle signs of “sink” in my week?",
     "invitation": "This week, notice what lifts and what sinks — turn decisively toward the Spirit, and show one person where the lift is."},
  "sessions": sessions, "talks": talks,
  "challenge": {"id": "challenge-oct-2026", "title": "The Lift Challenge",
     "text": "For 7 days, choose one invitation from a Saturday talk and act on it. Then share a short story of what happened.",
     "note": "Stories are reviewed before they appear."},
}
out = pathlib.Path(__file__).resolve().parent.parent / "assets" / "data.js"
out.write_text("// GENERATED by tools/talks_source.py — edit that file, then run: python3 tools/talks_source.py\nwindow.CONF = " + json.dumps(site, ensure_ascii=False, indent=1) + ";\n")
print("wrote", out, len(talks), "talks")
